apiVersion: v1
kind: Service
metadata:
  name: smokestack-api-service
  namespace: smokestack
spec:
  selector:
    app: smokestack-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP